[font]
normal = { family = "IBM Plex Mono", style = "Regular" }
bold = { family = "IBM Plex Mono", style = "Bold" }
italic = { family = "IBM Plex Mono", style = "Italic" }

#[colors]
#draw_bold_text_with_bright_colors = true

#[selection]
#save_to_clipboard = true

#[cursor]
#style = { shape = "Block", blinking = "On" }

[window]
padding = { x = 8, y = 8 }
dynamic_padding = true
decorations = "full"
opacity = 0.95
